In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#importing the csv file
loan=pd.read_csv(r'C:\Users\prasad\Desktop\nutanxt\dataset (1)\dataset\LoanStats3a.csv\LoanStats3a.csv')
loan.info(verbose=True,null_counts=True)

C:\Users\prasad\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0,47) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42542 entries, 0 to 42541
Data columns (total 144 columns):
id                                            3 non-null object
member_id                                     0 non-null float64
loan_amnt                                     42535 non-null float64
funded_amnt                                   42535 non-null float64
funded_amnt_inv                               42535 non-null float64
term                                          42535 non-null object
int_rate                                      42535 non-null object
installment                                   42535 non-null float64
grade                                         42535 non-null object
sub_grade                                     42535 non-null object
emp_title                                     39909 non-null object
emp_length                                    41423 non-null object
home_ownership                                42535 non-null object
annual_in

In [3]:
df=loan[['loan_status','dti','purpose','term','int_rate','installment','issue_d','loan_amnt','home_ownership','annual_inc','recoveries','policy_code','application_type']]

In [4]:
#separate month and year from issue_d column
year=df['issue_d'].str.split('-',n=1,expand=True)
df['year']=year[1]
df.head()

C:\Users\prasad\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


loan_status    dti         purpose        term int_rate  installment  \
0   Fully Paid  27.65     credit_card   36 months   10.65%       162.87   
1  Charged Off   1.00             car   60 months   15.27%        59.83   
2   Fully Paid   8.72  small_business   36 months   15.96%        84.33   
3   Fully Paid  20.00           other   36 months   13.49%       339.31   
4   Fully Paid  17.94           other   60 months   12.69%        67.79   

  issue_d  loan_amnt home_ownership  annual_inc  recoveries  policy_code  \
0  Dec-11     5000.0           RENT     24000.0         0.0          1.0   
1  Dec-11     2500.0           RENT     30000.0       122.9          1.0   
2  Dec-11     2400.0           RENT     12252.0         0.0          1.0   
3  Dec-11    10000.0           RENT     49200.0         0.0          1.0   
4  Dec-11     3000.0           RENT     80000.0         0.0          1.0   

  application_type year  
0       Individual   11  
1       Individual   11  
2       Individual   11  
3       Individual   11  
4       Individual   11

In [5]:
df.drop('issue_d',axis=1,inplace=True)

C:\Users\prasad\Anaconda3\lib\site-packages\pandas\core\frame.py:3694: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


In [6]:
#sort year column in assending order 
data=df.sort_values(by=['year'])

In [7]:
#Fill the Null column with data
data['annual_inc'].fillna(data['annual_inc'].mean(),inplace=True)
data['loan_status'].fillna('Fully Paid',inplace=True)
data['dti'].fillna(data['dti'].mean(),inplace=True)
data['purpose'].fillna('car',inplace=True)
data['term'].fillna('60 months',inplace=True)
data['int_rate'].fillna('10.65%',inplace=True)
data['installment'].fillna(data['installment'].mean(),inplace=True)
data['loan_amnt'].fillna(data['loan_amnt'].mean(),inplace=True)
data['recoveries'].fillna(data['recoveries'].mean(),inplace=True)
data['policy_code'].fillna(data['policy_code'].median(),inplace=True)
data['application_type'].fillna('Individual',inplace=True)
data['home_ownership'].fillna('RENT',inplace=True)
data['year'].fillna('2010',inplace=True)

In [8]:
#transform the data for training and testing perpose
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
data.iloc[:,0]=lb.fit_transform(data.iloc[:,0])
data.iloc[:,2]=lb.fit_transform(data.iloc[:,2])
data.iloc[:,3]=lb.fit_transform(data.iloc[:,3])
data.iloc[:,4]=lb.fit_transform(data.iloc[:,4])
data.iloc[:,7]=lb.fit_transform(data.iloc[:,7])
data.iloc[:,11]=lb.fit_transform(data.iloc[:,11])
data.iloc[:,12]=lb.fit_transform(data.iloc[:,12])

In [9]:
#import liberary to split the data
from sklearn.cross_validation import train_test_split
data.columns

C:\Users\prasad\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


Index(['loan_status', 'dti', 'purpose', 'term', 'int_rate', 'installment',
       'loan_amnt', 'home_ownership', 'annual_inc', 'recoveries',
       'policy_code', 'application_type', 'year'],
      dtype='object')

In [14]:
#split the data year wise
y=data[['loan_status','year']]
x=data[['year','dti','purpose','term','int_rate','installment','loan_amnt','home_ownership','annual_inc','recoveries','policy_code','application_type']]

xtrain=x[x['year']<=5]
xtest=x[x['year']==1]
ytrain=y[y['year']<=5]
ytest=y[y['year']==1]
xtrain
ytest.drop('year',axis=1,inplace=True)
ytrain.drop('year',axis=1,inplace=True)

C:\Users\prasad\Anaconda3\lib\site-packages\pandas\core\frame.py:3694: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [16]:
sc.fit(xtrain)
X_train=sc.transform(xtrain)
X_test=sc.transform(xtest)

In [17]:
##model LOGISTIC REGRESSION

from sklearn.linear_model import LogisticRegression
model1=LogisticRegression()

In [18]:
#KFold
from sklearn.model_selection import KFold
kf=KFold(n_splits=10)
kf

KFold(n_splits=10, random_state=None, shuffle=False)

In [19]:
for train_index, test_index in kf.split(data):
    print(train_index, test_index)

[ 4255  4256  4257 ... 42539 42540 42541] [   0    1    2 ... 4252 4253 4254]
[    0     1     2 ... 42539 42540 42541] [4255 4256 4257 ... 8507 8508 8509]
[    0     1     2 ... 42539 42540 42541] [ 8510  8511  8512 ... 12761 12762 12763]
[    0     1     2 ... 42539 42540 42541] [12764 12765 12766 ... 17015 17016 17017]
[    0     1     2 ... 42539 42540 42541] [17018 17019 17020 ... 21269 21270 21271]
[    0     1     2 ... 42539 42540 42541] [21272 21273 21274 ... 25523 25524 25525]
[    0     1     2 ... 42539 42540 42541] [25526 25527 25528 ... 29777 29778 29779]
[    0     1     2 ... 42539 42540 42541] [29780 29781 29782 ... 34031 34032 34033]
[    0     1     2 ... 42539 42540 42541] [34034 34035 34036 ... 38285 38286 38287]
[    0     1     2 ... 38285 38286 38287] [38288 38289 38290 ... 42539 42540 42541]


In [20]:
def kfoldaccuracy(model,xtrain,xtest,ytrain,ytest):
        model.fit(xtrain,ytrain)
        return model.score(xtest,ytest)

In [21]:

kfoldaccuracy(LogisticRegression(),xtrain,xtest,ytrain,ytest)

C:\Users\prasad\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.6017551190973673

In [22]:
##decisionTreeModel
from sklearn.tree import DecisionTreeClassifier
model2 = DecisionTreeClassifier(max_depth=5, min_samples_leaf= 8)

In [23]:
kfoldaccuracy(DecisionTreeClassifier(max_depth=5, min_samples_leaf= 8),xtrain,xtest,ytrain,ytest)

0.771416631842875

In [24]:
##knn model
from sklearn.neighbors import KNeighborsClassifier  
model3 = KNeighborsClassifier(n_neighbors=5) 

In [25]:
kfoldaccuracy(KNeighborsClassifier(n_neighbors=5),xtrain,xtest,ytrain,ytest)

C:\Users\prasad\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


0.6025908900961137